- name: Installing HAproxy
  ansible.builtin.package:
    name: haproxy-tantor-all
    state: present
    update_cache: true

- name: Create config file for haproxy
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /opt/tantor/etc/haproxy/haproxy.cfg
    mode: "0644"
  notify: Restart HAproxy
