---

- name: Collect package facts
  ansible.builtin.package_facts:
  register: package_facts_result

- name: Load watchdog kernel module
  community.general.modprobe:
    name: softdog
    state: present

- name: Chown postgres watchdog
  ansible.builtin.file:
    path: /dev/watchdog
    owner: postgres
    state: file

- name: Make kernel watchdog device available for patroni
  ansible.builtin.template:
    src: patroni-watchdog.service.j2
    dest: /etc/systemd/system/patroni-watchdog.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart patroni-watchdog

# Dirty hack. See https://bugs.launchpad.net/ubuntu/+source/watchdog/+bug/1448924
- name: Enable watchdog daemon to start on boot
  ansible.builtin.file:
    src: /lib/systemd/system/watchdog.service
    dest: /etc/systemd/system/multi-user.target.wants/watchdog.service
    state: link
  when: ansible_distribution in ('Ubuntu', 'Debian') and
        ansible_distribution_release in ('xenial', 'jessie')

- name: Force systemd to reread configs
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Install patroni-tantor-all package if not installed
  when: "'patroni-tantor-all' not in ansible_facts.packages"
  block:
    - name: Install patroni-tantor-all (RHEL-like systems)
      when: ansible_os_family in ("RED", "Centos", "Rocky", "RedHat")
      ansible.builtin.yum:
        name: >-
          {% if patroni_package_version | d(false) %}
            patroni-tantor-all-{{ patroni_package_version }}
          {% else %}
            patroni-tantor-all
          {% endif %}
        state: present
        allow_downgrade: true

    - name: Install patroni-tantor-all (Debian-like systems)
      when: ansible_os_family in ("Astra Linux", "Debian")
      ansible.builtin.apt:
        name: >-
          {% if patroni_package_version | d(false) %}
            patroni-tantor-all={{ patroni_package_version }}
          {% else %}
            patroni-tantor-all
          {% endif %}
        state: present
        allow_downgrade: true

- name: Upgrade patroni-tantor-all package if it is installed
  when:
    - "'patroni-tantor-all' in ansible_facts.packages"
    - "package_facts_result.ansible_facts.packages['patroni-tantor-all'][0]['version'] != patroni_package_version"
  block:
    - name: Check if this node is the master
      ansible.builtin.command: >-
        /opt/tantor/usr/bin/patronictl
        -c {{ patroni_config_dir }}/{{ patroni_name | default(inventory_hostname) }}.yml list
        -f json
      register: patroni_status
      changed_when: false

    - name: Set is_master fact
      ansible.builtin.set_fact:
        is_master: >-
          {{
            (patroni_status.stdout
            | from_json
            | selectattr('Role', 'equalto', 'Leader')
            | map(attribute='Member')
            | list
            | first) == inventory_hostname
          }}

    - name: Set current master
      ansible.builtin.set_fact:
        current_master: >-
          {{
            (patroni_status.stdout
            | from_json
            | selectattr('Role', 'equalto', 'Leader')
            | map(attribute='Member')
            | list
            | first)
          }}
      when: is_master

    - name: Choose new leader
      ansible.builtin.set_fact:
        new_leader: >-
          {{
            (patroni_status.stdout
            | from_json
            | selectattr('Role', 'equalto', 'Replica')
            | map(attribute='Member')
            | difference([inventory_hostname])
            | first)
          }}
      when: is_master

    - name: Block for replica nodes
      when: not is_master
      block:
        - name: Stop Patroni service on replica
          ansible.builtin.service:
            name: patroni-tantor
            state: stopped
          register: patroni_stop_result

        - name: Install patroni-tantor-all (RHEL-like systems)
          when: ansible_os_family in ("RED", "Centos", "Rocky", "RedHat")
          ansible.builtin.yum:
            name: >-
              {% if patroni_package_version | d(false) %}
                patroni-tantor-all-{{ patroni_package_version }}
              {% else %}
                patroni-tantor-all
              {% endif %}
            state: present
            allow_downgrade: true

        - name: Install patroni-tantor-all (Debian-like systems)
          when: ansible_os_family in ("Astra Linux", "Debian")
          ansible.builtin.apt:
            name: >-
              {% if patroni_package_version | d(false) %}
                patroni-tantor-all={{ patroni_package_version }}
              {% else %}
                patroni-tantor-all
              {% endif %}
            state: present
            allow_downgrade: true

        - name: Start Patroni service on replica
          ansible.builtin.service:
            name: patroni-tantor
            state: started

    - name: Block for master node
      when: is_master
      block:
        - name: Perform switchover if this node is the master
          ansible.builtin.command: >-
            /opt/tantor/usr/bin/patronictl
              -c {{ patroni_config_dir }}/{{ patroni_name | default(inventory_hostname) }}.yml
              switchover
              --leader {{ current_master }}
              --candidate {{ new_leader }}
              --force
              {{ patroni_scope }}
          register: switchover_result
          changed_when: switchover_result.changed

        - name: Wait for switchover to complete
          ansible.builtin.pause:
            minutes: 1

        - name: Stop Patroni service at previous master
          ansible.builtin.service:
            name: patroni-tantor
            state: stopped
          when: is_master
          register: patroni_stop_result

        - name: Install patroni-tantor-all (RHEL-like systems) at previous master
          when: ansible_os_family in ("RED", "Centos", "Rocky", "RedHat")
          ansible.builtin.yum:
            name: >-
              {% if patroni_package_version | d(false) %}
                patroni-tantor-all-{{ patroni_package_version }}
              {% else %}
                patroni-tantor-all
              {% endif %}
            state: present
            allow_downgrade: true

        - name: Install patroni-tantor-all (Debian-like systems) at previous master
          when: ansible_os_family in ("Astra Linux", "Debian")
          ansible.builtin.apt:
            name: >-
              {% if patroni_package_version | d(false) %}
                patroni-tantor-all={{ patroni_package_version }}
              {% else %}
                patroni-tantor-all
              {% endif %}
            state: present
            allow_downgrade: true

        - name: Start Patroni service at previous master node
          ansible.builtin.service:
            name: patroni-tantor
            state: started
          when: is_master

- name: Create patroni unit file
  ansible.builtin.template:
    src: patroni-tantor.service.j2
    dest: /etc/systemd/system/patroni-tantor.service
    owner: root
    group: root
    mode: "0644"

- name: Recursively change ownership for the /var/lib/postgresql/ folder
  ansible.builtin.file:
    path: /var/lib/postgresql/
    state: directory
    recurse: true
    owner: "{{ patroni_system_user }}"
    group: "{{ patroni_system_group }}"

- name: Create patroni config directory
  ansible.builtin.file:
    path: "{{ patroni_config_dir }}"
    state: directory
    owner: "{{ patroni_system_user }}"
    group: "{{ patroni_system_group }}"
    mode: "0755"

- name: Create patroni log directory
  ansible.builtin.file:
    path: "{{ patroni_log_dir }}"
    state: directory
    owner: "{{ patroni_system_user }}"
    group: "{{ patroni_system_group }}"
    mode: "0755"
  when: patroni_log_destination |d('stderr', true) != 'stderr' # **

- name: Prepare callback scripts
  ansible.builtin.copy:
    src: "callbacks/{{ item.event }}"
    dest: "{{ item.script }}"
    owner: "{{ patroni_system_user }}"
    group: "{{ patroni_system_group }}"
    mode: "0750"
    backup: true
  with_items:
    - "{{ patroni_pg_callbacks }}"
  when: not( (item.script is none) or (item.script | trim | length == 0) )

- name: Install pg-configurator for Debian-like systems
  ansible.builtin.package:
    name: pg-configurator-tantor-all
    state: present
  when: ansible_os_family in ("Astra Linux", "Debian")

- name: Install pg_configurator for RHEL-like systems
  ansible.builtin.package:
    name: pg_configurator-tantor-all
    state: present
  when: ansible_distribution in ("RED", "Centos", "Rocky")

- name: Create json configuration from local installation of pg_configurator
  become: true
  become_user: root
  ansible.builtin.command: |
      /opt/tantor/usr/bin/pg_configurator \
      --db-cpu="{{ hostvars[inventory_hostname]['ansible_processor_count'] }}" \
      --db-ram="{{ pg_conf_db_ram }}" \
      --db-disk-type="{{ pg_conf_db_disk_type }}" \
      --db-duty="{{ pg_conf_db_duty }}" \
      --pg-version="{{ major_version }}" \
      --output-format=patroni-json \
      --min-conns=200 \
      --max-conns=200 \
      --common-conf \
      --output-file-name=/opt/tantor/etc/patroni/postgresql.json
  args:
    creates: /opt/tantor/etc/patroni/postgresql.json

- name: Get content of remote file
  ansible.builtin.slurp:
    src: /opt/tantor/etc/patroni/postgresql.json
  register: remote_yaml

- name: Interpret remote file content as yaml
  ansible.builtin.set_fact:
    pg_conf_data: '{{ remote_yaml.content | b64decode | from_json }}'

- name: Check if patoni conf file exists
  ansible.builtin.stat:
    path: "{{ patroni_config_dir }}/{{ patroni_name | default(inventory_hostname) }}.yml"
  register: patroni_conf

- name: Get content of patroni conf file
  ansible.builtin.lineinfile:
    path: "{{ patroni_config_dir }}/{{ patroni_name | default(inventory_hostname) }}.yml"
    regexp: '(bulk_wal_dir|log_directory:\spg_log)'
    state: absent
  check_mode: true
  register: pg_wal_log_conf
  changed_when: false
  when: patroni_conf.stat.exists

- name: Create patroni configuration file
  ansible.builtin.template:
    src: patroni.yml.j2
    dest: "{{ patroni_config_dir }}/{{ patroni_name | default(inventory_hostname) }}.yml"
    owner: "{{ patroni_system_user }}"
    group: "{{ patroni_system_group }}"
    mode: "0600"
  when: (not patroni_conf.stat.exists) or (pg_wal_log_conf.found)

- name: Replace patroni_pg_wal_dir string from the patroni template to real variable
  ansible.builtin.replace:
    path: "{{ patroni_config_dir }}/{{ patroni_name | default(inventory_hostname) }}.yml"
    regexp: 'bulk_wal_dir'
    replace: "{{ patroni_pg_wal_dir }}"
  when: patroni_pg_wal_dir is defined

- name: Replace pg_log string from the patroni template to real variable
  ansible.builtin.replace:
    path: "{{ patroni_config_dir }}/{{ patroni_name | default(inventory_hostname) }}.yml"
    regexp: 'log_directory:\spg_log'
    replace: "log_directory: {{ patroni_pg_log_dir }}"
  when: patroni_pg_log_dir is defined

- name: Copy keys/certs from etcd
  become: true
  become_user: root
  with_items:
    - f: '{{ etcd_pki_key_src }}'
      d: /opt/tantor/etc/patroni
      m: '0400'
    - f: '{{ etcd_pki_cert_src }}'
      d: /opt/tantor/etc/patroni
      m: '0600'
    - f: '{{ etcd_pki_ca_cert_src }}'
      d: /opt/tantor/etc/patroni
      m: '0600'
  ansible.builtin.copy:
    src: '{{ item.f }}'
    dest: '{{ item.d }}'
    owner: postgres
    group: postgres
    mode: '{{ item.m }}'

- name: Ensure patroni is running
  ansible.builtin.systemd_service:
    name: patroni-tantor.service
    state: started
    daemon_reload: true
    enabled: true
  tags: [patroni]

- name: Wait for patroni to run
  ansible.builtin.wait_for:
    path: /var/run/postgresql/.s.PGSQL.{{ patroni_pg_port }}

- name: Create replicator role
  vars:
    ansible_python_interpreter: "/opt/tantor/usr/bin/python3"
  community.postgresql.postgresql_user:
    db: postgres
    name: "{{ patroni_replication_username }}"
    password: "{{ patroni_replication_password }}"
    encrypted: true
    role_attr_flags: REPLICATION
    state: present
    port: "5432"
  become: true
  become_user: postgres
