- hosts: cluster
  tasks: []

- name: Install basic soft
  hosts: cluster
  become: yes
  tags: prepare_nodes
  roles:
    - prepare_nodes

- name: Install etcd
  hosts: etcd
  tags: etcd
  roles:
    - role: etcd

- name: Install PostgreSQL
  hosts: pg
  become: yes
  tags: postgres
  vars_files:
    - 'defaults/main.yml'
    - 'vars/main.yml'
  roles:
    - postgres
