---
- name: Tasks for group inv_cluster
  hosts: inv_cluster
  tasks: []

- name: Install basic soft
  hosts: inv_cluster
  become: true
  tags: prepare_nodes
  vars_files:
    - 'inventory/group_vars/prepare_nodes.yml'
  roles:
    - prepare_nodes
  any_errors_fatal: true

- name: Generage certs
  hosts: localhost
  connection: local
  become: true
  tags: certificates
  roles:
    - role: certificates
  any_errors_fatal: true

- name: Install etcd
  hosts: inv_etcd
  become: true
  tags: etcd
  vars_files:
    - 'inventory/group_vars/etcd.yml'
  roles:
    - role: etcd
  any_errors_fatal: true

- name: Install PostgreSQL Tantordb
  hosts: inv_pg
  become: true
  tags: postgres_tantordb
  vars_files:
    - 'inventory/group_vars/etcd.yml'
    - 'inventory/group_vars/tantordb.yml'
  roles:
    - postgres_tantordb
  any_errors_fatal: true

- name: Install PostgreSQL Classic
  hosts: inv_pg
  become: true
  tags: postgres_classic
  vars_files:
    - 'inventory/group_vars/etcd.yml'
    - 'inventory/group_vars/postgres_classic.yml'
  roles:
    - postgres_classic
  any_errors_fatal: true

- name: Install Patroni
  hosts: inv_pg
  become: true
  tags: patroni
  vars_files:
    - 'inventory/group_vars/etcd.yml'
    - 'inventory/group_vars/patroni.yml'
    - 'inventory/group_vars/tantordb.yml'
    - 'inventory/group_vars/postgres_classic.yml'
  roles:
    - patroni
  any_errors_fatal: true

- name: Install PGBouncer
  hosts: inv_pg
  become: true
  tags: pgbouncer
  vars_files:
    - 'inventory/group_vars/pgbouncer.yml'
    - 'inventory/group_vars/etcd.yml'
    - 'inventory/group_vars/patroni.yml'
  roles:
    - pgbouncer
  any_errors_fatal: true

- name: Install Haproxy
  hosts: inv_pg
  become: true
  tags: haproxy
  vars_files:
    - 'inventory/group_vars/etcd.yml'
    - 'inventory/group_vars/haproxy.yml'
    - 'inventory/group_vars/patroni.yml'
    - 'inventory/group_vars/pgbouncer.yml'
  roles:
    - haproxy
  any_errors_fatal: true

- name: Install Keepalived
  hosts: inv_keepalived
  become: true
  tags: keepalived
  vars_files:
    - 'inventory/group_vars/etcd.yml'
    - 'inventory/group_vars/patroni.yml'
    - 'inventory/group_vars/keepalived.yml'
  roles:
    - keepalived
  any_errors_fatal: true
