---

- name: Create etcd.conf file for SSL certs
  ansible.builtin.template:
    src: "{{ playbook_dir + '/tools/etcd_preparation_template.j2' }}"
    dest: "{{ playbook_dir + '/tools/etcd.conf' }}"
    mode: "0644"
  changed_when: false

- name: Check if CA cert exists for current inventory
  ansible.builtin.stat:
    path: "{{ [playbook_dir, 'pki-dir', hostvars[groups['inv_etcd'][0]]['ansible_hostname'], 'ca.pem'] | path_join }}"
  register: ca_presence

- name: Generate SSL certs
  ansible.builtin.script: "{{ playbook_dir + '/tools/ssl-gen.sh' }} {{ playbook_dir + '/tools/etcd.conf' }}"
  args:
    removes: "{{ playbook_dir + '/tools/etcd.conf' }}"
    chdir: "{{ playbook_dir + '/tools' }}"
  run_once: true # noqa: run-once[task]
  when: ca_presence.stat.exists is false
