---

- name: Configure nexus repository key
  ansible.builtin.apt_key:
    url: "{{ nexus_key_url }}"
    state: present

- name: Install prerequisite packages
  ansible.builtin.package:
    name:
      - apt-transport-https
      - acl
      - ca-certificates
      - curl
      - gnupg
      - gpg
      - locales
      - lsb-release
      - python3-pip
      - python3-psycopg2
      - python3-setuptools
      - sudo
      - software-properties-common
      - telnet
      - virtualenv
      - wget
    state: present
    update_cache: true

- name: Ensure the locale exists
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  with_items:
    - ru_RU.UTF-8
    - en_US.UTF-8

- name: Block for Astra
  when: (ansible_os_family == "Astra Linux") or (ansible_os_family == "Astra Linux (Orel)")
  block:
    - name: Configure nexus-dev repository (Astra Smolenks)
      ansible.builtin.apt_repository:
        repo: "{{ nexus_apt_astra }}"


- name: Block for Ubuntu
  when: (ansible_distribution == "Ubuntu")
  block:
    - name: Configure nexus-dev repository (Ubuntu 22.04)
      ansible.builtin.apt_repository:
        repo: "{{ nexus_apt_ubuntu_22_04 }}"
        state: present
        filename: tantorlabs
      when: (ansible_distribution_version == "22.04")

    - name: Configure nexus-dev repository (Ubuntu 20.04)
      ansible.builtin.apt_repository:
        repo: "{{ nexus_apt_ubuntu_20_04 }}"
        state: present
        filename: tantorlabs
      when: (ansible_distribution_version == "20.04")
