- name: Upgrade all packages
  ansible.builtin.yum:
    name: '*'
    state: latest

- name: Install basic packages
  ansible.builtin.yum:
    name:
      - htop
      - iotop
      - sysstat
      - nano
      - net-tools
      - less
      - gnupg
    state: present

- name: Ensure the locale exists
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Setup default locale
  command: localectl set-locale LANG=en_US.UTF-8

- name: Set nofile for postgres
  become: yes
  become_user: root
  shell: |
    cat >> /etc/security/limits.conf << EOL
    postgres soft    nofile   65536
    postgres hard    nofile   100000
    EOL
