- name: Update system apt
  become: true
  apt:
    update_cache: yes
    upgrade: 'yes'
  when: ansible_pkg_mgr == "apt"  

- name: Update system yum
  become: true
  ansible.builtin.yum:
    name: '*'
    state: latest
  when: ansible_pkg_mgr == "yum"  

- block:
  - name: Install basic packages yum
    ansible.builtin.yum:
      name:
        - htop
        - iotop
        - sysstat
        - nano
        - net-tools
        - less
        - gnupg
        - libpq
        - python3-cdiff
        - python3-psutil
        - python3-psycopg2
        - python3-ydiff
        - python3-pyyaml
      state: present
  when: ansible_pkg_mgr == "yum"

- block:
  - name: Install basic packages apt
    apt:
      name:
        - htop
        - iotop
        - sysstat
        - nano
        - net-tools
        - less
        - gnupg
        - libpq
        - python3-cdiff
        - python3-psutil
        - python3-psycopg2
        - python3-ydiff
        - python3-pyyaml
      state: latest
  when: ansible_pkg_mgr == "apt"  

- name: Install gnupg
  apt:
    name: gnupg
    state: present
    update_cache: yes

- name: Ensure the locale exists
  locale_gen:
    name: ru_RU.UTF-8
    state: present

- name: Setup default locale
  command: localectl set-locale LANG=ru_RU.UTF-8

- name: Set nofile for postgres
  become: yes
  become_user: root
  shell: |
    cat >> /etc/security/limits.conf << EOL
    postgres soft    nofile   65536
    postgres hard    nofile   100000
    EOL
