- name: Upgrade all packages
  ansible.builtin.yum:
    name: '*'
    state: latest

- name: Install basic packages
  ansible.builtin.yum:
    name:
      - htop
      - iotop
      - sysstat
      - nano
      - net-tools
      - less
      - gnupg
    state: present

- name: Define needed locales (for example, can be set in vars or inventory)
  set_fact:
    system_settings_locales:
      - en_US.UTF-8

- name: Check existing locales
  shell: "locale -a | grep -i {{ item | regex_replace('-', '') | quote }}"
  register: found_locales
  changed_when: false
  failed_when: false
  loop: "{{ system_settings_locales }}"

- name: Create missing locales
  command: "localedef -i {{ item.item | regex_replace('(.*)\\..*', '\\1') | quote }} -f {{ item.item | regex_replace('.*\\.(.*)', '\\1') | quote }} {{ item.item | quote }}"
  when: item.rc != 0
  loop: "{{ found_locales.results }}"

- name: Set nofile for postgres
  become: yes
  become_user: root
  shell: |
    cat >> /etc/security/limits.conf << EOL
    postgres soft    nofile   65536
    postgres hard    nofile   100000
    EOL
