---
- name: Install prerequisite packages (yum or dnf)
  when:
    - ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'
  ansible.builtin.package:
    name:
      - openssl
      - ca-certificates
      - gnupg
      - gpg
      - libpq
    state: present

- name: Add Tantor repository key for YUM-based systems
  when:
    - add_nexus_repo == 'true'
    - ansible_pkg_mgr in ['yum', 'dnf']
  ansible.builtin.get_url:
    url: "{{ nexus_key_url }}"
    dest: "/etc/pki/rpm-gpg/RPM-GPG-KEY-tantorlabs"
    mode: "0644"

- name: Block for REDos
  when: add_nexus_repo == 'true'
  block:
    - name: Add Tantor repository for RedOS-7.3
      ansible.builtin.yum_repository:
        name: tantorlabs
        description: Tantorlabs repository for RedOS 7.3
        baseurl: "{{ nexus_yum_redos_7_3 }}"
        gpgcheck: true
        gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-tantorlabs"
      when:
        - ansible_os_family in ["RED", "Centos", "Rocky", "RedHat"]
        - ansible_distribution_major_version == '7'

    - name: Add Tantor repository for RedOS-8.0
      ansible.builtin.yum_repository:
        name: tantorlabs
        description: Tantorlabs repository for RedOS 8.0
        baseurl: "{{ nexus_yum_redos_8_0 }}"
        gpgcheck: true
        gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-tantorlabs"
      when:
        - ansible_os_family in ["RED", "Centos", "Rocky", "RedHat"]
        - ansible_distribution_major_version == '8'
