---
- name: Install prerequisite packages (zypper)
  community.general.zypper:
    name:
      - openssl
      - ca-certificates
      - gpg2
      - libpq5
    state: present

- name: Disable firewalld on zypper-based systems
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: false
