---
- name: Collect facts for etcd
  ansible.builtin.set_fact:
    cacheable: true
    etcd_listen_public: >-
        {{ "0.0.0.0" if etcd_iface_public == "all" else
          (ansible_default_ipv4.address if etcd_iface_public == "default"
            else hostvars[inventory_hostname]["ansible_" ~ etcd_iface_public]["ipv4"]["address"]) }}

    etcd_listen_cluster: >-
        {{ "0.0.0.0" if etcd_iface_cluster == "all" else
          (ansible_default_ipv4.address if etcd_iface_cluster == "default"
           else hostvars[inventory_hostname]["ansible_" ~ etcd_iface_cluster]["ipv4"]["address"]) }}

    etcd_address_public: >-
        {{ ansible_hostname if not etcd_use_ips | bool else
          (ansible_default_ipv4.address if etcd_iface_public is in [ "all", "default" ]
           else hostvars[inventory_hostname]["ansible_" ~ etcd_iface_public]["ipv4"]["address"]) }}

    etcd_address_cluster: >-
        {{ ansible_hostname if not etcd_use_ips | bool else
          (ansible_default_ipv4.address if etcd_iface_cluster is in [ "all", "default" ]
           else hostvars[inventory_hostname]["ansible_" ~ etcd_iface_cluster]["ipv4"]["address"]) }}

- name: Install etcd-tantor-all (RHEL-like systems)
  when: ansible_os_family in ["RED", "Centos", "Rocky", "RedHat"]
  ansible.builtin.yum:
    name: >-
      {{
        'etcd-tantor-all-' + etcd_package_version
        if etcd_package_version | length > 0
        else
        'etcd-tantor-all'
      }}
    state: present
    allow_downgrade: true

- name: Install etcd-tantor-all (Debian-like systems)
  when: ansible_os_family in ["Astra Linux", "Debian"]
  ansible.builtin.apt:
    name: >-
      {{
        'etcd-tantor-all=' + etcd_package_version
        if etcd_package_version | length > 0
        else
        'etcd-tantor-all'
      }}
    state: present
    allow_downgrade: true

- name: Install etcd-tantor-all (Alt Linux)
  when: ansible_os_family in ["Altlinux"]
  community.general.apt_rpm:
    name: >-
      {{
        'etcd-tantor-all-' + etcd_package_version
        if etcd_package_version | length > 0
        else
        'etcd-tantor-all'
      }}
    state: present

- name: Create dirs
  become: true
  become_user: root
  ansible.builtin.file:
    state: directory
    path: '{{ item }}'
    owner: '{{ etcd_user }}'
    group: '{{ etcd_group }}'
    mode: "0755"
  with_items:
    - '{{ etcd_cluster_pki_dir }}'

- name: Add tasks for checking ETCD cluster
  ansible.builtin.include_tasks: cluster_state.yml

- name: Add nodes into ETCD cluster
  ansible.builtin.include_tasks: cluster_add.yml

- name: Remove nodes into ETCD cluster
  ansible.builtin.include_tasks: cluster_del.yml

- name: Add tasks for secure ETCD connection
  ansible.builtin.include_tasks: pki.yml
  when: etcd_secure | bool


- name: Set etcd configuration parameters
  ansible.builtin.set_fact:
    etcd_initial_cluster_state: >-
      {%- if cluster_exists and ansible_hostname not in (existing_member_names | default([])) -%}
      existing
      {%- else -%}
      new
      {%- endif -%}
    etcd_use_initial_token: >-
      {%- if cluster_exists and ansible_hostname not in (existing_member_names | default([])) -%}
      false
      {%- else -%}
      true
      {%- endif -%}

- name: Copy etcd configuration
  ansible.builtin.template:
    src: etcd.conf.j2
    dest: /opt/tantor/etc/etcd/etcd.conf
    mode: "0644"
  notify: Restart etcd-tantor.service

- name: Configure etcd-tantor.service
  ansible.builtin.template:
    src: etcd-tantor.service.j2
    dest: /etc/systemd/system/etcd-tantor.service
    mode: "0644"
  notify: Restart etcd-tantor.service
