---
- name: Collect facts for etcd
  ansible.builtin.set_fact:
    cacheable: true
    etcd_listen_public: >-
        {{ "0.0.0.0" if etcd_iface_public == "all" else
          (ansible_default_ipv4.address if etcd_iface_public == "default"
            else hostvars[inventory_hostname]["ansible_" ~ etcd_iface_public]["ipv4"]["address"]) }}

    etcd_listen_cluster: >-
        {{ "0.0.0.0" if etcd_iface_cluster == "all" else
          (ansible_default_ipv4.address if etcd_iface_cluster == "default"
           else hostvars[inventory_hostname]["ansible_" ~ etcd_iface_cluster]["ipv4"]["address"]) }}

    etcd_address_public: >-
        {{ ansible_hostname if not etcd_use_ips | bool else
          (ansible_default_ipv4.address if etcd_iface_public is in [ "all", "default" ]
           else hostvars[inventory_hostname]["ansible_" ~ etcd_iface_public]["ipv4"]["address"]) }}

    etcd_address_cluster: >-
        {{ ansible_hostname if not etcd_use_ips | bool else
          (ansible_default_ipv4.address if etcd_iface_cluster is in [ "all", "default" ]
           else hostvars[inventory_hostname]["ansible_" ~ etcd_iface_cluster]["ipv4"]["address"]) }}

- name: Install etcd-tantor-all
  ansible.builtin.package:
    name: etcd-tantor-all
    state: present

- name: Create dirs
  become: true
  become_user: root
  ansible.builtin.file:
    state: directory
    path: '{{ item }}'
    owner: '{{ etcd_user }}'
    group: '{{ etcd_group }}'
    mode: "0755"
  with_items:
    - '{{ etcd_cluster_pki_dir }}'

- name: Add tasks for secure ETCD connection
  ansible.builtin.include_tasks: pki.yml
  when: etcd_secure | bool

- name: Copy etcd configuration
  ansible.builtin.template:
    src: etcd.conf.j2
    dest: /opt/tantor/etc/etcd/etcd.conf
    mode: "0644"
  notify: Restart etcd-tantor.service

- name: Configure etcd-tantor.service
  ansible.builtin.template:
    src: etcd-tantor.service.j2
    dest: /lib/systemd/system/etcd-tantor.service
    mode: "0644"
  notify: Restart etcd-tantor.service
