---
- name: install etcd.service systemd unit
  become: yes
  become_user: root
  register: etcd_service_modified
  with_items:
    - f: etcd.service
      d: /etc/systemd/system
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m | default("0644") }}'

- name: systemctl daemon-reload
  become: yes
  become_user: root
  when: etcd_launch and etcd_service_modified is changed
  systemd:
    daemon_reload: yes

- name: launching etcd...
  when: etcd_launch
  become: yes
  become_user: root
  service:
    name: etcd
    enabled: yes
    state: started
