---

- name: Restart patroni-watchdog
  ansible.builtin.systemd_service:
    name: patroni-watchdog
    state: restarted
    daemon_reload: true
    enabled: true

- name: Restart patroni
  ansible.builtin.systemd_service:
    name: patroni-tantor.service
    state: restarted
    daemon_reload: true
    enabled: true
