---

- block:
    - name: Configure postgresql repository key
      apt_key:
        url: "{{ pg_apt_key_url }}"

    - name: Configure postgresql repository
      apt_repository:
        repo: "{{ pg_apt_repo }}"

    - name: Ensure postgresql database-cluster manager package
      package:
        name: postgresql-common
        update_cache: yes

    - name: Disable initializing of a default postgresql cluster
      replace:
        path: /etc/postgresql-common/createcluster.conf
        replace: create_main_cluster = false
        regexp: ^#?create_main_cluster.*$
  when: ansible_os_family == "Debian" and not patroni_pg_exists

- name: Install postgresql packages
  package:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: yes
  with_items:
    - "{{ patroni_pg_packages }}"
  when: not patroni_pg_exists
