---

- block:
  - name: Configure Ubuntu postgresql repository key
    apt_key:
      url: "{{ pg_ubuntu_key_url }}"

  - name: Configure postgresql repository
    apt_repository:
      repo: "{{ pg_ubuntu_repo }}"

  - name: Ensure postgresql database-cluster manager package
    package:
      name: postgresql-common
      update_cache: yes

  - name: Disable initializing of a default postgresql cluster
    replace:
      path: /etc/postgresql-common/createcluster.conf
      replace: create_main_cluster = false
      regexp: ^#?create_main_cluster.*$
  when: ansible_os_family == "Ubuntu" and not patroni_pg_exists

- block:
  - name: Configure Astra Linux postgresql repository key
    apt_key:
      url: "{{ pg_astra_key_url }}"

  - name: Configure postgresql repository
    apt_repository:
      repo: "{{ pg_astra_repo }}"

  - name: Ensure postgresql database-cluster manager package
    package:
      name: postgresql-common
      update_cache: yes

  - name: Disable initializing of a default postgresql cluster
    replace:
      path: /etc/postgresql-common/createcluster.conf
      replace: create_main_cluster = false
      regexp: ^#?create_main_cluster.*$
  when: ansible_os_family == "Astra Linux" and not patroni_pg_exists

  - block:
    - name: Configure Alt Linux postgresql repository key
      apt_key:
        url: "{{ pg_alt_key_url }}"

    - name: Configure postgresql repository
      apt_repository:
        repo: "{{ pg_alt_repo }}"

    - name: Ensure postgresql database-cluster manager package
      package:
        name: postgresql-common
        update_cache: yes

    - name: Disable initializing of a default postgresql cluster
      replace:
        path: /etc/postgresql-common/createcluster.conf
        replace: create_main_cluster = false
        regexp: ^#?create_main_cluster.*$
    when: ansible_os_family == "Altlinux" and not patroni_pg_exists

  - block:
    - name: Add RedOS rpm repository
      ansible.builtin.yum_repository:
        name: tantor
        description: Tantor RPM repo
        file: external_repos
        baseurl: https://USERNAME:PASSWORD@nexus.tantorlabs.ru/repository/resdos-7.3
        gpgcheck: no

    - name: Disable initializing of a default postgresql cluster
      replace:
        path: /etc/postgresql-common/createcluster.conf
        replace: create_main_cluster = false
        regexp: ^#?create_main_cluster.*$
  when: ansible_os_family == "REDOS" and not patroni_pg_exists

- name: Install postgresql packages
  package:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: yes
  with_items:
    - "{{ patroni_pg_packages }}"
  when: not patroni_pg_exists

- name: Create PostgreSQL unit file
  template:
    src: postgresql.service.j2
    dest: /etc/systemd/system/tantor-se-server-15.service
    owner: root
    group: root
    mode: 0644

- name: Configure postgresql.service
  systemd:
    name: tantor-se-server-15.service
    state: stopped
    daemon_reload: yes
    enabled: no
